# Numpy : 

In [7]:
a = [1,2,3,4]

b = [2,3,4,5]

# concatination 
print(a + b )


[1, 2, 3, 4, 2, 3, 4, 5]


In [8]:
a = [1,2,3,4]

b = [2,3,4,5]

print(a - b )  # We get Error 

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
b = np.array([2,3,4,5])
b

array([2, 3, 4, 5])

In [12]:
print(a+b)

[3 5 7 9]


## Addition of Vector: 

In [13]:
v1 = np.array([1,2,3,4 ])
v1

array([1, 2, 3, 4])

In [14]:
v2 = np.array([2,3,4,5])
v2

array([2, 3, 4, 5])

In [15]:
v1 + v2

array([3, 5, 7, 9])

In [16]:
#  ----------------Substraction , mul , div , floor 

In [17]:
v1-v2

array([-1, -1, -1, -1])

In [18]:
v1 * v2

array([ 2,  6, 12, 20])

In [19]:
v1/v2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [20]:
v1//v2

array([0, 0, 0, 0], dtype=int32)

### Addition , Mul , Sub , Div , Floor Div MATRIX

In [21]:
m1 = np.array([[1,2,3,4,5] , [3,4,5,6,1] , [4,5,6,7,8]])
m1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 1],
       [4, 5, 6, 7, 8]])

In [22]:
m2 = np.array([[2,3,4,5,6] , [5,6,7,8,9] , [-1,-3,-5,6,7]])
m2

array([[ 2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9],
       [-1, -3, -5,  6,  7]])

In [23]:
m1 + m2

array([[ 3,  5,  7,  9, 11],
       [ 8, 10, 12, 14, 10],
       [ 3,  2,  1, 13, 15]])

In [24]:
m1 - m2

array([[-1, -1, -1, -1, -1],
       [-2, -2, -2, -2, -8],
       [ 5,  8, 11,  1,  1]])

In [25]:
m1 *m2

array([[  2,   6,  12,  20,  30],
       [ 15,  24,  35,  48,   9],
       [ -4, -15, -30,  42,  56]])

In [26]:
m1 / m2

array([[ 0.5       ,  0.66666667,  0.75      ,  0.8       ,  0.83333333],
       [ 0.6       ,  0.66666667,  0.71428571,  0.75      ,  0.11111111],
       [-4.        , -1.66666667, -1.2       ,  1.16666667,  1.14285714]])

In [27]:
m1 // m2

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [-4, -2, -2,  1,  1]], dtype=int32)

# Dot Product

# Vector Multiplication : 

In [28]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [29]:
v2 = np.array([8,9,4,5,6])
v2

array([8, 9, 4, 5, 6])

In [30]:
np.dot(v1,v2)

88

In [31]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.dot(v1,v2)

32

In [32]:
# vector * Vectoer = Vector 

In [33]:
# vector * scaler = vector

In [34]:
a = np.array([3,4,5,6,7])
a

array([3, 4, 5, 6, 7])

In [35]:
b = 10

In [36]:
a*b

array([30, 40, 50, 60, 70])

In [37]:
#  sclaer +vector  = vector

In [38]:
a+ b

array([13, 14, 15, 16, 17])

In [39]:
# scaler * sclaer = scaler 

In [40]:
a = 10 
b = 20

a * b

200

#   Matrix Multiplication 

In [41]:
m1 = np.array([[1,2,3,4,5] , [3,4,5,6,1] , [4,5,6,7,8]])
m1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 1],
       [4, 5, 6, 7, 8]])

In [42]:
m2 = np.array([[2,3,4,5,6] , [5,6,7,8,9] , [-1,-3,-5,6,7]])
m2

array([[ 2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9],
       [-1, -3, -5,  6,  7]])

In [43]:
np.dot(m1,m2)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [44]:
# matrix by 4 * 5
# matrix by 5 * 2

In [45]:
m1 = np.array([[1,2,3,4,5] ,[4,5,6,7,8] , [1,7,3,2,4],[0,9,8,7,1]])
m1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [1, 7, 3, 2, 4],
       [0, 9, 8, 7, 1]])

In [46]:
m2 = np.array([[1,2] , [4,5] , [2,3] ,[5,6] , [6,7]])
m2

array([[1, 2],
       [4, 5],
       [2, 3],
       [5, 6],
       [6, 7]])

In [47]:
np.dot(m1,m2)

array([[ 65,  80],
       [119, 149],
       [ 69,  86],
       [ 93, 118]])

# Declaration of Scaler ,Vector , MAtrix

In [48]:
# Scaler
s = 10

print(a)
print(type(a))

10
<class 'int'>


In [49]:
print(a.shape)  # we get error

AttributeError: 'int' object has no attribute 'shape'

In [50]:
# vector

v = np.array([1,2,3,4,5])

v

array([1, 2, 3, 4, 5])

In [51]:
print(type(v))

<class 'numpy.ndarray'>


In [52]:
print(v.shape)

(5,)


In [53]:
## Matrix : 
m1 = np.array([[1,2,3,4,5] , [3,4,5,6,1] , [4,5,6,7,8]])
m1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 1],
       [4, 5, 6, 7, 8]])

In [54]:
print(type(m1))

<class 'numpy.ndarray'>


In [55]:
print(m1.shape)

(3, 5)


#  Creating Columns Vector

In [56]:
v

array([1, 2, 3, 4, 5])

In [57]:
v1 = v.reshape(1, 5)
v1

array([[1, 2, 3, 4, 5]])

In [58]:
v1.shape

(1, 5)

In [59]:
v2 = v.reshape(5,1)
v2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [60]:
v2.shape

(5, 1)

In [61]:
print(type(v2))

<class 'numpy.ndarray'>


In [62]:
# Transpose Matrix : 

In [63]:
## Matrix : 
A = np.array([[1,2,3,4,5] , [3,4,5,6,1] , [4,5,6,7,8]])
A


array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 1],
       [4, 5, 6, 7, 8]])

In [64]:
A.T

array([[1, 3, 4],
       [2, 4, 5],
       [3, 5, 6],
       [4, 6, 7],
       [5, 1, 8]])

In [65]:
B = np.array([[1,2,3,4] , [3,4,5,6] ,[6,7,8,9] , [1,4,5,7] , [0,0,0,9]])
B

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9],
       [1, 4, 5, 7],
       [0, 0, 0, 9]])

In [66]:
B.T

array([[1, 3, 6, 1, 0],
       [2, 4, 7, 4, 0],
       [3, 5, 8, 5, 0],
       [4, 6, 9, 7, 9]])

In [67]:
# Transpose Vector :

In [68]:
V = np.array([1,2,3,4,5,60])
V

array([ 1,  2,  3,  4,  5, 60])

In [69]:
V1 = V.reshape(1,6)

In [70]:
V1

array([[ 1,  2,  3,  4,  5, 60]])

In [71]:
V1.T

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [60]])